/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ai/jobs/{job_id}/cover-letter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cover Letter
         * @description Stream a tailored cover letter as Server-Sent Events.
         *
         *     Each SSE event: `data: <chunk>\n\n`
         *     Final event:    `data: [DONE]\n\n`
         */
        post: operations["cover_letter_api_ai_jobs__job_id__cover_letter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/jobs/{job_id}/fit-score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fit Score
         * @description Score how well the candidate profile matches this job's description.
         */
        get: operations["fit_score_api_ai_jobs__job_id__fit_score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/jobs/{job_id}/signal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Apply Signal
         * @description Return a concise apply/consider/skip recommendation.
         */
        get: operations["apply_signal_api_ai_jobs__job_id__signal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description Read the saved candidate profile.
         */
        get: operations["get_profile_api_ai_profile_get"];
        /**
         * Update Profile
         * @description Save (overwrite) the candidate profile.
         */
        put: operations["update_profile_api_ai_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ai Status
         * @description Check whether the AI backend is reachable and the model is loaded.
         */
        get: operations["ai_status_api_ai_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocked-companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Blocked
         * @description List blocked companies.
         */
        get: operations["list_blocked_api_blocked_companies_get"];
        put?: never;
        /**
         * Block Company
         * @description Create or refresh a normalized company block.
         */
        post: operations["block_company_api_blocked_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocked-companies/{company_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unblock Company
         * @description Remove one company block in the requested platform scope.
         */
        delete: operations["unblock_company_api_blocked_companies__company_key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_documents__document_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Document
         * @description Update only the supplied document fields.
         */
        patch: operations["update_document_api_documents__document_id__patch"];
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Event
         * @description Submit a state change (status transition or hide/star flag) addressed by
         *     `(platform, platform_id)` or `job_id`; returns the resulting job state.
         */
        post: operations["create_event_api_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Note Event
         * @description Delete a note; state-changing events require correction or revert.
         */
        delete: operations["delete_note_event_api_events__event_id__delete"];
        options?: never;
        head?: never;
        /**
         * Edit Event
         * @description Update an event's metadata and/or timestamp without changing its verb.
         */
        patch: operations["edit_event_api_events__event_id__patch"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description DB-free liveness probe for the extension's reachability poll.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Job
         * @description Delete a job and all of its listings, events, and documents.
         */
        delete: operations["delete_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        /** Update Job */
        patch: operations["update_job_api_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/jobs/{job_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Correct Status
         * @description Set any status and record the deliberate correction.
         */
        post: operations["correct_status_api_jobs__job_id__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Document */
        post: operations["create_document_api_jobs__job_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/status/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revert Status
         * @description Remove the latest status-setting event and reproject the prior state.
         */
        post: operations["revert_status_api_jobs__job_id__status_revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/applied-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Applied Count
         * @description Count jobs carrying application evidence for a company.
         */
        get: operations["applied_count_api_jobs_applied_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Match Listings
         * @description Return duplicate candidates without materializing the current listing.
         */
        get: operations["match_listings_api_jobs_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State For Listings */
        get: operations["state_for_listings_api_jobs_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Listing */
        post: operations["create_listing_api_listings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{listing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Listing
         * @description Delete one listing and dissolve its job if no listings remain.
         */
        delete: operations["delete_listing_api_listings__listing_id__delete"];
        options?: never;
        head?: never;
        /** Update Listing */
        patch: operations["update_listing_api_listings__listing_id__patch"];
        trace?: never;
    };
    "/api/listings/false-match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create False Match
         * @description Exclude two jobs from each other's duplicate suggestions.
         *
         *     Materializes the current listing if it is not tracked yet.
         */
        post: operations["create_false_match_api_listings_false_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/link-job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link Job
         * @description Merge two jobs under the more advanced funnel state.
         *
         *     Returns the current listing's address under the surviving job.
         */
        post: operations["link_job_api_listings_link_job_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup Listing
         * @description Resolve a listing natural key to its stored job and listing ids.
         */
        get: operations["lookup_listing_api_listings_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/note-titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Note Titles
         * @description Return previously used note titles, most-used first.
         */
        get: operations["get_note_titles_api_meta_note_titles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vocabulary
         * @description Return previously used metadata keys and values, most-used first.
         */
        get: operations["get_vocabulary_api_meta_vocabulary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Search Log
         * @description Return recent search-diagnostic rows, newest first.
         */
        get: operations["list_search_log_api_search_log_get"];
        put?: never;
        /**
         * Create Search Log
         * @description Record one opted-in popup search session.
         */
        post: operations["create_search_log_api_search_log_post"];
        /**
         * Clear Search Log
         * @description Delete every stored search-diagnostic row.
         */
        delete: operations["clear_search_log_api_search_log_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search-log/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Log Report
         * @description Click-through by automatic seed rule, or `typed` when no seed was used.
         */
        get: operations["search_log_report_api_search_log_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AIStatusResponse
         * @description Health check for the AI subsystem.
         */
        AIStatusResponse: {
            /** Available */
            available: boolean;
            /** Message */
            message: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
        };
        /**
         * ApplySignalResponse
         * @description Concise 'should I apply?' signal.
         */
        ApplySignalResponse: {
            /**
             * Green Flags
             * @description Positive signals for this role
             */
            green_flags?: string[];
            /**
             * Recommendation
             * @description apply / consider / skip
             */
            recommendation: string;
            /**
             * Red Flags
             * @description Concerns or mismatches
             */
            red_flags?: string[];
            /**
             * Summary
             * @description One sentence summary
             */
            summary: string;
        };
        /**
         * ApplyType
         * @enum {string}
         */
        ApplyType: "easy_apply" | "external" | "unknown";
        /**
         * Attention
         * @description Read-only reminder for a stalled post-application stage.
         */
        Attention: {
            /** Days */
            days: number;
            /** Since */
            since: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "applied" | "in_process";
        };
        /** BlockedCompany */
        BlockedCompany: {
            /** Company Key */
            company_key: string;
            /** Created At */
            created_at: string;
            /** Label */
            label?: string | null;
            /** Platform */
            platform: string;
        };
        /**
         * BlockedCompanyCreate
         * @description Raw company name and optional platform scope for a normalized block.
         */
        BlockedCompanyCreate: {
            /** Company */
            company: string;
            /**
             * Platform
             * @default *
             */
            platform: string;
        };
        /**
         * CompanyAppliedCount
         * @description Applied-job count and the normalized company key used for lookup.
         */
        CompanyAppliedCount: {
            /** Company Key */
            company_key?: string | null;
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /**
         * CorrectionCreate
         * @description A deliberate status override, logged as `corrected:<status>`.
         */
        CorrectionCreate: {
            /** Reason */
            reason?: string | null;
            status: components["schemas"]["Status"];
        };
        /**
         * CoverLetterRequest
         * @description Optional overrides when requesting a cover letter.
         */
        CoverLetterRequest: {
            /**
             * Max Words
             * @default 300
             */
            max_words: number;
            /**
             * Tone
             * @description professional / conversational / enthusiastic
             * @default professional
             */
            tone: string;
        };
        /** Document */
        Document: {
            /** Content */
            content?: string | null;
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Job Id */
            job_id: string;
            /** Provided */
            provided: boolean;
            /** Requested */
            requested?: string | null;
            /** Type */
            type: string;
            /** Updated At */
            updated_at: string;
        };
        /** DocumentCreate */
        DocumentCreate: {
            /** Content */
            content?: string | null;
            /**
             * Provided
             * @default false
             */
            provided: boolean;
            /** Requested */
            requested?: ("required" | "optional") | null;
            type: components["schemas"]["DocumentType"];
        };
        /**
         * DocumentType
         * @enum {string}
         */
        DocumentType: "cover_letter" | "motivation_letter" | "cv" | "other";
        /**
         * DocumentUpdate
         * @description Fields to change on an existing document.
         */
        DocumentUpdate: {
            /** Content */
            content?: string | null;
            /** Provided */
            provided?: boolean | null;
            /** Requested */
            requested?: ("required" | "optional") | null;
            type?: components["schemas"]["DocumentType"] | null;
        };
        /**
         * Event
         * @enum {string}
         */
        "Event-Input": "created" | "seen" | "to_apply" | "applied" | "in_process" | "offered" | "skipped" | "withdrawn" | "rejected" | "closed" | "ghosted" | "hidden" | "unhidden" | "starred" | "unstarred" | "note";
        /** Event */
        "Event-Output": {
            /** Event */
            event: string;
            /** Id */
            id: number;
            /** Job Id */
            job_id: string;
            /** Listing Id */
            listing_id?: string | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
            /** Ts */
            ts: string;
        };
        /**
         * EventCreate
         * @description Ordered events addressed by one listing natural key or one job id.
         */
        EventCreate: {
            /** Events */
            events: components["schemas"]["EventItem"][];
            /** Job Id */
            job_id?: string | null;
            /** Platform */
            platform?: string | null;
            /** Platform Id */
            platform_id?: string | null;
            /** Ts */
            ts?: string | null;
        };
        /**
         * EventItem
         * @description One event verb and its optional metadata.
         */
        EventItem: {
            event: components["schemas"]["Event-Input"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * EventUpdate
         * @description Optional metadata and timestamp changes for an existing event.
         *
         *     Metadata replaces the complete bag. The event verb is immutable.
         */
        EventUpdate: {
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
            /** Ts */
            ts?: string | null;
        };
        /**
         * FalseMatchCreate
         * @description Mutually exclude the current listing's job and a candidate job.
         */
        FalseMatchCreate: {
            /** Other Job Id */
            other_job_id: string;
            /** Platform */
            platform: string;
            /** Platform Id */
            platform_id: string;
        };
        /**
         * FitScoreResponse
         * @description Structured fit analysis for a job.
         */
        FitScoreResponse: {
            /**
             * Confidence
             * @description low / medium / high based on JD completeness
             * @default medium
             */
            confidence: string;
            /**
             * Matched Skills
             * @description Skills from JD you have
             */
            matched_skills?: string[];
            /**
             * Missing Skills
             * @description Skills from JD you lack
             */
            missing_skills?: string[];
            /**
             * Rationale
             * @description 2-sentence explanation of the score
             */
            rationale: string;
            /**
             * Score
             * @description Overall fit score (0–100)
             */
            score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Job */
        Job: {
            /** Company */
            company?: string | null;
            /** Company Key */
            company_key?: string | null;
            /** Created At */
            created_at: string;
            /** Hidden */
            hidden: boolean;
            /** Id */
            id: string;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            /** Starred */
            starred: boolean;
            /** Status */
            status: string;
            /** Title */
            title?: string | null;
            /** Title Key */
            title_key?: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** JobDetail */
        JobDetail: {
            /** Company */
            company?: string | null;
            /** Company Key */
            company_key?: string | null;
            /** Created At */
            created_at: string;
            /**
             * Documents
             * @default []
             */
            documents: components["schemas"]["Document"][];
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["Event-Output"][];
            /** Hidden */
            hidden: boolean;
            /** Id */
            id: string;
            /**
             * Listings
             * @default []
             */
            listings: components["schemas"]["Listing"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            /** Starred */
            starred: boolean;
            /** Status */
            status: string;
            /** Title */
            title?: string | null;
            /** Title Key */
            title_key?: string | null;
            /** Updated At */
            updated_at: string;
        };
        /**
         * JobMatch
         * @description Duplicate-suggestion candidate after false-match filtering.
         */
        JobMatch: {
            /** Closed At */
            closed_at?: string | null;
            /** Company */
            company?: string | null;
            /** Created At */
            created_at: string;
            /** Job Id */
            job_id: string;
            /**
             * Listing Count
             * @default 0
             */
            listing_count: number;
            /** Similarity */
            similarity?: number | null;
            /** Status */
            status: string;
            /** Title */
            title?: string | null;
        };
        /**
         * JobState
         * @description Compact listing state; `untracked` is a read-only synthetic status.
         */
        JobState: {
            /** Hidden */
            hidden: boolean;
            /** Starred */
            starred: boolean;
            /** Status */
            status: string;
        };
        /**
         * JobSummary
         * @description Job plus the listing rollup needed by dashboard cards.
         */
        JobSummary: {
            /**
             * Apply Types
             * @default []
             */
            apply_types: string[];
            attention?: components["schemas"]["Attention"] | null;
            /** Company */
            company?: string | null;
            /** Company Key */
            company_key?: string | null;
            /** Created At */
            created_at: string;
            /** Hidden */
            hidden: boolean;
            /** Id */
            id: string;
            /**
             * Listing Count
             * @default 0
             */
            listing_count: number;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            /**
             * Platforms
             * @default []
             */
            platforms: string[];
            primary_listing?: components["schemas"]["PrimaryListing"] | null;
            /** Starred */
            starred: boolean;
            /** Status */
            status: string;
            /** Title */
            title?: string | null;
            /** Title Key */
            title_key?: string | null;
            /** Updated At */
            updated_at: string;
        };
        /**
         * JobUpdate
         * @description Identity and metadata changes; metadata replaces the complete bag.
         */
        JobUpdate: {
            /** Company */
            company?: string | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
            /** Title */
            title?: string | null;
        };
        /**
         * LinkJobCreate
         * @description Merge the current listing's complete job with another job.
         */
        LinkJobCreate: {
            /** Other Job Id */
            other_job_id: string;
            /** Platform */
            platform: string;
            /** Platform Id */
            platform_id: string;
        };
        /** Listing */
        Listing: {
            /** Apply Type */
            apply_type?: string | null;
            /** Captured At */
            captured_at?: string | null;
            /** Closed At */
            closed_at?: string | null;
            /** Company */
            company?: string | null;
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            /** Platform */
            platform: string;
            /** Platform Id */
            platform_id: string;
            /** Title */
            title?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Url */
            url?: string | null;
        };
        /** ListingCreate */
        ListingCreate: {
            apply_type?: components["schemas"]["ApplyType"] | null;
            /** Closed At */
            closed_at?: string | null;
            /** Company */
            company?: string | null;
            /** Job Id */
            job_id?: string | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            /** Platform */
            platform: string;
            /** Platform Id */
            platform_id: string;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
            /**
             * Via
             * @default capture
             */
            via: string;
        };
        /**
         * ListingState
         * @description Listing state tagged with its platform-native id.
         */
        ListingState: {
            /** Hidden */
            hidden: boolean;
            /** Platform Id */
            platform_id: string;
            /** Starred */
            starred: boolean;
            /** Status */
            status: string;
        };
        /** ListingUpdate */
        ListingUpdate: {
            apply_type?: components["schemas"]["ApplyType"] | null;
            /** Closed At */
            closed_at?: string | null;
            /** Company */
            company?: string | null;
            /** Job Id */
            job_id?: string | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
        };
        /** ListingUpsertResult */
        ListingUpsertResult: {
            /** Job Id */
            job_id: string;
            /** Listing Id */
            listing_id: string;
        };
        /**
         * MetaKey
         * @description Metadata-key usage, sample values, and inferred value type.
         */
        MetaKey: {
            /** Key */
            key: string;
            /** Type */
            type: string;
            /** Uses */
            uses: number;
            /** Values */
            values: string[];
        };
        /**
         * MetaVocabulary
         * @description Previously used metadata keys and values, ordered by frequency.
         */
        MetaVocabulary: {
            /** Entity */
            entity: string;
            /** Keys */
            keys: components["schemas"]["MetaKey"][];
        };
        /**
         * PrimaryListing
         * @description Preferred listing address for a dashboard card.
         */
        PrimaryListing: {
            /** Platform */
            platform: string;
            /** Platform Id */
            platform_id: string;
            /** Url */
            url?: string | null;
        };
        /** RuleReport */
        RuleReport: {
            /** Attempts */
            attempts: number;
            /** Click Rate */
            click_rate: number;
            /** Clicks */
            clicks: number;
            /** Rule */
            rule: string;
        };
        /**
         * SearchLogCreate
         * @description One full-context search-diagnostics row from an explicitly enabled popup.
         */
        SearchLogCreate: {
            /** Host */
            host?: string | null;
            /** Job Id */
            job_id?: string | null;
            /** Query */
            query?: string | null;
            /** Results */
            results?: number | null;
            /** Seed */
            seed?: string | null;
            /** Seed Results */
            seed_results?: number | null;
            /** Seed Rule */
            seed_rule?: string | null;
        };
        /** SearchLogRow */
        SearchLogRow: {
            /** Host */
            host: string | null;
            /** Id */
            id: number;
            /** Job Id */
            job_id: string | null;
            /** Query */
            query: string | null;
            /** Results */
            results: number | null;
            /** Seed */
            seed: string | null;
            /** Seed Results */
            seed_results: number | null;
            /** Seed Rule */
            seed_rule: string | null;
            /** Ts */
            ts: string;
        };
        /** SearchReport */
        SearchReport: {
            /** By Rule */
            by_rule: components["schemas"]["RuleReport"][];
            /** Click Rate */
            click_rate: number;
            /** Total Attempts */
            total_attempts: number;
            /** Total Clicks */
            total_clicks: number;
        };
        /** Stats */
        Stats: {
            /** Apply Type */
            apply_type: {
                [key: string]: number;
            };
            /** Funnel */
            funnel: {
                [key: string]: number;
            };
            /** Total Jobs */
            total_jobs: number;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "new" | "seen" | "to_apply" | "applied" | "in_process" | "offered" | "skipped" | "closed" | "withdrawn" | "rejected" | "ghosted";
        /**
         * UserProfile
         * @description The candidate's profile used for all AI features.
         */
        UserProfile: {
            /**
             * Name
             * @default
             */
            name: string;
            /** Skills */
            skills?: string[];
            /**
             * Summary
             * @description 2-3 sentence professional summary
             * @default
             */
            summary: string;
            /** Target Roles */
            target_roles?: string[];
            /**
             * Title
             * @description Current/target role title
             * @default
             */
            title: string;
            /**
             * Years Experience
             * @default 0
             */
            years_experience: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cover_letter_api_ai_jobs__job_id__cover_letter_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoverLetterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fit_score_api_ai_jobs__job_id__fit_score_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_signal_api_ai_jobs__job_id__signal_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplySignalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_ai_profile_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_ai_profile_put: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_status_api_ai_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_blocked_api_blocked_companies_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedCompany"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    block_company_api_blocked_companies_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockedCompanyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedCompany"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unblock_company_api_blocked_companies__company_key__delete: {
        parameters: {
            query?: {
                platform?: string;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                company_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_document_api_documents__document_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_events_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_event_api_events__event_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_event_api_events__event_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                apply_type?: string | null;
                company?: string | null;
                hidden?: boolean | null;
                limit?: number | null;
                offset?: number;
                q?: string | null;
                starred?: boolean | null;
                status?: string | null;
                stubs?: boolean | null;
                title?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_api_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_status_api_jobs__job_id__corrections_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_api_jobs__job_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_status_api_jobs__job_id__status_revert_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    applied_count_api_jobs_applied_count_get: {
        parameters: {
            query?: {
                company?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyAppliedCount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_listings_api_jobs_matches_get: {
        parameters: {
            query: {
                company?: string | null;
                platform: string;
                platform_id: string;
                title?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobMatch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    state_for_listings_api_jobs_states_get: {
        parameters: {
            query: {
                platform: string;
                platform_ids?: string[];
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingState"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_listing_api_listings_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingUpsertResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_listing_api_listings__listing_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_listing_api_listings__listing_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingUpsertResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_false_match_api_listings_false_match_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FalseMatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_job_api_listings_link_job_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingUpsertResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_listing_api_listings_lookup_get: {
        parameters: {
            query: {
                platform: string;
                platform_id: string;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingUpsertResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_note_titles_api_meta_note_titles_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vocabulary_api_meta_vocabulary_get: {
        parameters: {
            query?: {
                entity?: string;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaVocabulary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_search_log_api_search_log_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchLogRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_search_log_api_search_log_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_search_log_api_search_log_delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_log_report_api_search_log_report_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
